import cv2
import mediapipe as mp
import numpy as np
import joblib
from collections import deque, Counter
import os

# ---------- CONFIG ----------
# Use local model path relative to project root (generated by scripts/train_classifier.py).
MODEL_PATH = os.path.join("models", "sign_model.pkl")

# optional: list of labels (for ordering / display)
CLASS_NAMES = [
    "BEAUTIFUL",
    "CAREFUL",
    "FIGHT",
    "HELLO",
    "NO",
    "NOW",
    "SEE",
    "TALK",
    "THANK YOU",
    "US",
    "YES",
]

NUM_LANDMARKS = 21
SMOOTHING_WINDOW = 7  # number of last predictions to smooth; set to 1 for raw outputs

# ----------------------------

print(f"[INFO] Loading model from {MODEL_PATH} ...")
model = joblib.load(MODEL_PATH)
print("[INFO] Model loaded.")

mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils

hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5,
)

cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("[ERROR] Could not open webcam.")
    exit()

print("[INFO] Starting real-time detection. Press ESC to quit.")

# for smoothing predictions
pred_buffer = deque(maxlen=SMOOTHING_WINDOW)


def extract_landmarks(results, image_width, image_height):
    """
    Same logic as in collect_data.py:
    - 21 landmarks
    - convert to pixel space
    - make coordinates relative to wrist (0,0,0)
    - flatten to 63 features
    """
    if not results.multi_hand_landmarks:
        return None

    hand_landmarks = results.multi_hand_landmarks[0]

    coords = []
    for lm in hand_landmarks.landmark:
        x = lm.x * image_width
        y = lm.y * image_height
        z = lm.z
        coords.append([x, y, z])

    coords = np.array(coords)  # (21, 3)

    # relative to wrist (landmark 0)
    wrist = coords[0].copy()
    coords[:, 0] -= wrist[0]
    coords[:, 1] -= wrist[1]
    coords[:, 2] -= wrist[2]

    features = coords.flatten()  # shape (63,)
    return features


while True:
    ret, frame = cap.read()
    if not ret:
        print("[ERROR] Failed to grab frame.")
        break

    frame = cv2.flip(frame, 1)
    h, w, _ = frame.shape

    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = hands.process(rgb)

    current_pred = None

    if results.multi_hand_landmarks:
        for hand_lms in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame, hand_lms, mp_hands.HAND_CONNECTIONS
            )

        features = extract_landmarks(results, w, h)
        if features is not None:
            # predict
            pred_label = model.predict([features])[0]
            current_pred = pred_label
            pred_buffer.append(pred_label)
    else:
        # no hand detected -> optional: clear buffer
        pred_buffer.append("")

    # smoothing: use most common label in buffer (excluding empty "")
    smooth_label = ""
    if len(pred_buffer) > 0:
        counts = Counter([p for p in pred_buffer if p != ""])
        if counts:
            smooth_label = counts.most_common(1)[0][0]

    # draw predicted label
    if smooth_label:
        text = f"Predicted: {smooth_label}"
        color = (0, 255, 0)
    else:
        text = "Show a sign..."
        color = (0, 255, 255)

    cv2.putText(
        frame,
        text,
        (10, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.9,
        color,
        2,
        cv2.LINE_AA,
    )

    cv2.imshow("Real-time Sign Detection", frame)

    key = cv2.waitKey(1) & 0xFF
    if key == 27:  # ESC
        break

cap.release()
cv2.destroyAllWindows()
print("[INFO] Exited.")
